project:
  type: website
    
website:
  site-url: https://yrarch.github.io/
  repo-url: https://github.com/yrarch/yrarch.github.io
  favicon: assets/img/favicons/favicon-32x32.png
  title: "![Logo YRA](assets/YRA_Logo.svg){height=60px}"
  description: "Young Researchers in Archaeometry is a workshop series organised by ECRs for ECRs"
  navbar:
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: "Home"
      - href: current.qmd
        text: "YRA 2024"
      - href: seminar.qmd
        text: "Seminar"
      - href: team.qmd
        text: "Team"
      - href: archive.qmd
        text: "Archive"
      - href: tutorials.qmd
        text: "Tutorials"
    right: 
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61559076328370
      - icon: twitter
        href: https://twitter.com/yrarchaeometry 
      - about.qmd

format:
  html:
    theme: 
      - lumen
      - custom.scss
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true
    margin-header: |
      ::: {.callout}
      ## Mailing list
      Want to get in contact with other ECRs in Archaeometry and stay tuned about YRA?  
      [Subscribe to our mailing list!](https://www.listserv.dfn.de/sympa/subscribe/yrarchaeometry)
      :::
      ::: {.callout}
      ## Contact
      Any questions? Drop us a mail at [youngresearchersarch [at] gmail.com](mailto:youngresearchersarch@gmail.com)
      :::

execute:
  freeze: auto

# colours: "#b93657", "#57266d" 
