---
title: "Young Researchers in Archaeometry 6"
---

::: {.column-margin}

:::: {.callout}

## Mailing list
Want to get in contact with other ECRs in Archaeometry and stay tuned about YRA?  
[Subscribe to our mailing list!](https://www.listserv.dfn.de/sympa/subscribe/yrarchaeometry){target="_blank"}

::::

:::: {.callout}

## Contact
Any questions? Drop us a mail at [youngresearchersarch@gmail.com](mailto:youngresearchersarch@gmail.com)

::::

:::

## Save the date!

We are happy to announce that the **6^th^ Workshop Young Researchers in Archaeometry** will be held in **hybrid format** at the **University of Tübingen**, Germany from **October 4^th^ to 6^th^, 2023**. The workshop will once again welcome early career researchers (master, PhD, first postdoc) in archaeological sciences and cultural heritage studies.

With this workshop we aim to offer a relaxed atmosphere to encourage interdisciplinary exchange between early career researchers. With a hybrid format, we are happy to welcome participants in person, as well as those online from all around the world, who cannot come to Tübingen. We are pleased to invite you for oral contributions in all kinds of natural sciences about archaeological and anthropological topics. In particular, early career researchers in archaeology, art history, anthropology, biology, chemistry, conservation, cultural heritage, earth science, material science, medicine, physics are welcome to submit an abstract.

## Abstract submission

will open in April. Stay tuned via our [mailing list](https://www.listserv.dfn.de/sympa/subscribe/yrarchaeometry){target="_blank"}.
