---
title: "Young Researchers in Archaeometry"
---

## A workshops series for ECRs by ECRs

YRA aims to give early career researchers (ECRs) in the archaeological sciences the opportunity to present their research in a friendly environment surrounded only by young students from the same field. We welcome all persons involved in archaeometry research of different nationalities and levels, from master students to first postdoctoral fellows.  

With our [mailing list](https://www.listserv.dfn.de/sympa/subscribe/yrarchaeometry), we offer ECRs a possibility to interact with each other between the workshops. While announced here as the major communication outlet for the YRA workshops beside the webpage, any subscriber is welcomed to use it for, e.g., sharing job advertisements, searching for collaborators, or having discussions about any topic related to archaeological sciences and/or being an early career researcher. 

## Defining “Early Career Researchers”

After having received so many abstracts in the call for papers for the YRA 2023 workshop, we decided to define in a more transparent way our definition of ECRs to help us determine who can contribute to the workshop.
We are aware of the difficulty to define the term “early career”. As such, we attempt to take into account the varied backgrounds and situations of researchers coming from diverse scientific communities and countries. After some discussion in early 2024, we agreed on the definition of ECRs as researchers up to 6 years after completion of their PhD without a permanent position, such as a lectureship or professorship.


## The journey

The idea for the workshop began in 2016 in a discussion about why so few ECRs are joining the German archaeological sciences conference “Archäometrie & Denkmalpflege” (Archaeometry & preservation of historic monuments). Besides the psychological barrier of delivering the first conference presentation in front of very distinguished researchers, it was realised that the archaeological sciences are often dispersed among many different institutes and work groups, making it very difficult for ECRs to get in contact with peers.  

Since the first workshop in Frankfurt in 2017, all YRA workshops stayed true to the original idea. While originally aiming for the German community, the workshops soon became orientated towards an international audience with about 50% of the participants in the second edition being internationals. Already in 2019, it became an international workshop series organised at an institution outside of Germany for the first time. The latest step was to  purposefully keep the hybrid format to become more inclusive to colleagues unable to attend the workshop in person while keeping the benefits of in-person meetings for networking. 

With every new edition, the structures for YRA have become more and more professionalised. Beginning with the processing of abstracts and registration in 2019, this was followed by the logo, mail address, and a first webpage in 2022, the last of which resulted in this webpage and the mailing list in 2023. Consequently, workload shifted more and more towards the local organisation while templates now exist for most other tasks. This, and the active support from previous organisers whenever needed, makes the YRA workshops particularly suited to gather first experiences as workshop organiser. This is what keeps YRA true to its motto: for ECRs by ECRs. 

So, what’s new? Starting in 2024, the YRA will organise a seminar series with lectures from fellow ECRs on a wide range of topics in archaeological science that are featured in the workshops. 

If you are interested in organising the next workshop or have ideas for additional events, please get in touch via [mail](youngresearchersarch@gmail.com). 

## The YRA logo

Designing a logo for YRA was not an easy task. Without a doubt, the biggest challenge was to create a logo that represents the huge breadth of disciplines working together in the archaeological sciences and represents the target group. Given the interdisciplinary ethos of the YRA workshops, it was decided that an abstract logo would be the most suitable.  

The logo writes “YRA” embedded in a spectra-like line with each letter having a different colour and the grey coloured parts as connecting lines. The trowel-shaped arrows outline the negative space (“hole”) of the letters R and A and are inspired by the markers for characteristic peaks. The colours do not have a special meaning. They were chosen because this combination is colour-blind friendly and pleasing to the eyes of the persons involved in the design process. 

## Code of conduct

Participants of all YRA-organised events agree to conduct themselves in a professional and appropriate manner and to ensure that all can enjoy a harassment-free event. The workshop organisers are dedicated to maintaining an inclusive, respectful, safe, friendly, and welcoming environment for all participants.

We do not tolerate disruptive or disrespectful behaviour, personal messages, images, or interactions by any participant, in any form, at any aspect of the program including business and social activities, regardless of mode of participation and location.

Photography, video, recording or screen-captures of session content or presentations in any format are prohibited unless this right is granted on the slides of the respective presentation. We encourage everyone to assist in creating a welcoming and safe environment.

If a participant engages in harassing behaviour, the event organisers may take any action they deem appropriate, including warning the offender and/or expulsion from the event. If you are being harassed, if you notice that someone else is being harassed, or have any other concerns, please contact one of the organisers immediately.

We value your attendance and want the YRA events to be a safe place for everybody.
